import pprint
import subprocess
import torch
from hyper_parameter_tuning_v2 import main


def flexmatch_kl_divergence_missing_labels_cifar100_v10000(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": [10, 100],
        "lt_choose_unseen_classes_randomly": [-1, 1],
        "lt_choose_labeled_data_randomly": [-1, 1],
        "lambda_kl_divergence": 1.5,
        "comment": 10000,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=1)

def flexmatch_kl_divergence_missing_labels_cifar100_v10000_1(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": [10, 100],
        "lt_choose_unseen_classes_randomly": [-1, 1],
        "lt_choose_labeled_data_randomly": [-1, 1],
        "lambda_kl_divergence": 0,
        "comment": 100001,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=1)


def flexmatch_kl_divergence_missing_labels_cifar100_v10001(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": [10, 100],
        "lt_choose_unseen_classes_randomly": [-1, 1],
        "lt_choose_labeled_data_randomly": [-1, 1],
        "lambda_kl_divergence": 1,
        "comment": 10001,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=1)


def flexmatch_kl_divergence_missing_labels_cifar100_v10002(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 200,  # 500,
        "num_train_iter": 204800,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": [10, 100],
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": [0.5,0.7,1.2],
        "comment": 10002,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=1)


def flexmatch_kl_divergence_missing_labels_cifar100_v10003(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "freematch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": [10, 100],
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence":0,
        "comment": 10003,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=1)


def flexmatch_kl_divergence_missing_labels_cifar100_v10004(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": [1,1.5],
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": [10, 100],
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence":0,
        "comment": 10004,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=1)




def flexmatch_kl_divergence_missing_labels_cifar100_v10005(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 200,  # 500,
        "num_train_iter": 204800,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": [10, 100],
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": [0.8,0.9],
        "comment": 10005,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=1)


def flexmatch_kl_divergence_missing_labels_cifar100_v10006(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": [10, 100],
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 1.1,
        "comment": 10006,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=1)



def flexmatch_kl_divergence_missing_labels_cifar100_v10006_1(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 100,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 1.1,
        "comment": 100061,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=1, seed_end=5)


def flexmatch_kl_divergence_missing_labels_cifar100_v10007(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 10,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 1.5,
        "comment": 10007,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=1, seed_end=5)



def flexmatch_kl_divergence_missing_labels_cifar100_v10008(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": [10,100],
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 0,
        "comment": 10008,
    }
    main(parameters_dict_missing_labels, seed_start=1, seed_end=5)



def flexmatch_kl_divergence_missing_labels_cifar100_v10009(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 10,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 1.1,
        "comment": 10009,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=1, seed_end=5)


def flexmatch_kl_divergence_missing_labels_cifar100_v10010(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 0,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 10,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 1,
        "comment": 10010,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=1, seed_end=5)

def flexmatch_kl_divergence_missing_labels_cifar100_v10011_1(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 1.5,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 0,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 10,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 0,
        "comment": 100111,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=1, seed_end=5)




def flexmatch_kl_divergence_missing_labels_cifar100_v10012(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 1500,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": [0,1.5],
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 0,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 100,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 0,
        "comment": 10012,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=5)


def flexmatch_kl_divergence_missing_labels_cifar100_v10012_1(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 1500,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 0,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 100,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 1,
        "comment": 100121,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=1)



def flexmatch_kl_divergence_missing_labels_cifar100_v10012_2(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 1500,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 0,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 100,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 1,
        "comment": 100122,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=1, seed_end=5)



def flexmatch_kl_divergence_missing_labels_cifar100_v10012_3(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 1500,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": [1,1.2],
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 0,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 100,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 0,
        "comment": 100123,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=5)


def flexmatch_kl_divergence_missing_labels_cifar100_v10013(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 700,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": [0,1.5],
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 0,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 10,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 0,
        "comment": 10013,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=5)


def flexmatch_kl_divergence_missing_labels_cifar100_v10013_1(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 700,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 0,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 10,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 1,
        "comment": 100131,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=1)


def flexmatch_kl_divergence_missing_labels_cifar100_v10013_2(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 700,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 0,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 10,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 1,
        "comment": 100132,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=1, seed_end=5)


def flexmatch_kl_divergence_missing_labels_cifar100_v10013_3(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 700,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": [1,1.2],
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 0,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 10,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 0,
        "comment": 100133,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=3, seed_end=5)


def flexmatch_kl_divergence_missing_labels_cifar100_v10014(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 1100,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": [0,1.5],
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 0,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 50,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 0,
        "comment": 10013,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=5)

def flexmatch_kl_divergence_missing_labels_cifar100_v10015(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 700,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 10,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 1,
        "comment": 10015,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=5)


def flexmatch_kl_divergence_missing_labels_cifar100_v10016(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 1500,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 100,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 1,
        "comment": 10016,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=5)



def flexmatch_kl_divergence_missing_labels_cifar100_v10017(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 1100,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 50,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": [0,1],
        "comment": 10017,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=5)

def flexmatch_kl_divergence_missing_labels_cifar100_v10018(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 400,
        "algorithm": "flexmatch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 1,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 50,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": [0,1],
        "comment": 10018,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=5)




