import pprint
import subprocess
import torch
from hyper_parameter_tuning_v2 import main



def freematch_kl_divergence_missing_labels_cifar100_v3000(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": [400,700],
        "algorithm": "freematch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 0,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 10,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 0,
        "comment": 3000,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=5)



def freematch_kl_divergence_missing_labels_cifar100_v3001(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": [400,1500],
        "algorithm": "freematch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 0,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 100,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 0,
        "comment": 3001,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=5)



def freematch_kl_divergence_missing_labels_cifar100_v3002(version):
    parameters_dict_missing_labels = {
        "load_path": "",
        "seed": "",
        "save_name": "",
        "epoch": 500,  # 500,
        "num_train_iter": 512000,
        "num_eval_iter": 1024,
        "num_classes": 100,
        "num_labels": 1100,
        "algorithm": "freematch",
        "save_dir": "./saved_models/classic_cv/tuning",
        "dataset": "cifar100",
        "slurm_job_id": None,
        "net_new": "None",
        "missing_labels": None,
        "random_missing_labels_num": 40,
        "choose_random_labeled_training_set": -1,
        "choose_random_labeled_training_set_duplicate": -1,
        "lambda_entropy": 0,
        "lb_imb_ratio": 1,
        "MNAR_round_type": "ceil",
        "threshold": 0.95,
        "new_p_cutoff": -1,
        "weight_decay": 0.001,
        "lambda_datapoint_entropy": 0,
        "project_wandb": f"test_kl_divergence",
        "python_code_version": 11,
        "delete": 0,
        "ulb_loss_ratio": 1.0,
        "lambda_entropy_with_labeled_data": 0,
        "lambda_entropy_with_labeled_data_v2": 0,
        "split_to_superclasses": 0,
        "new_ent_loss_ratio": -1,
        "save_all_models": 0,
        "batch_size": 64,
        "lambda_entropy_stop_epoch": -1,
        "lambda_entropy_decay_value": -1,
        "lambda_entropy_decay_rate": -1,
        "lt_ratio": 50,
        "lt_choose_unseen_classes_randomly": -1,
        "lt_choose_labeled_data_randomly": -1,
        "lambda_kl_divergence": 0,
        "comment": 3002,
    }
    main(parameters_dict_missing_labels, killable=False, seed_start=0, seed_end=5)

