algorithm: flexmatch
save_dir: ./saved_models/classic_cv
save_name: debug_flexmatch_cifar100_400_0
resume: False
load_path: ./saved_models/classic_cv/debug_flexmatch_cifar100_400_0/latest_model.pth
overwrite: True
use_tensorboard: True
num_labels: 400
batch_size: 64
eval_batch_size: 256
hard_label: True
T: 0.5
thresh_warmup: True
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_8
net_from_name: False
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10001
dist_backend: nccl
gpu: None
log_info: 0