resume: True
overwrite: True
use_tensorboard: True
use_wandb: False
batch_size: 64
eval_batch_size: 256
hard_label: False
p_cutoff: 0.95
contrast_p_cutoff: 0.8
contrast_loss_ratio: 1.0
ulb_loss_ratio: 1.0
proj_size: 64
queue_batch: 5
smoothing_alpha: 0.9
uratio: 7
T: 0.2
da_len: 32
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net_from_name: False
data_dir: ./data
train_sampler: RandomSampler
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10453
dist_backend: nccl
gpu: None
log_info: 0